apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: user-container
        image: microsm/micro-users
        env:
        - name: DB_HOST
          value: "postgresql"
        - name: DB_NAME
          value: "users"
        - name: DB_PASSWORD
          value: "MmRgHe7Q2E"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: users
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
