name: Build and Push Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/micro-users:latest

  deploy:
    runs-on: self-hosted
    # container: bitnami/kubectl:latest
    container:
      # image: bitnami/kubectl:latest 
      options: --user 1000
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          clean: false
          set-safe-directory: false

      - name: Apply Manifest
        run: sleep 400 && kubectl apply -f manifest.yaml

      - name: Restart Deployment
        run: kubectl rollout restart deployment user-deployment
