name: Deploy
on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    container: bitnami/kubectl:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Apply Manifest
        run: kubectl apply -f manifest.yaml

      - name: Restart Deployment
        run: kubectl rollout restart deployment user-deployment
